name: tarbus_app
description: tarbus app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # ios/android view separation helper
  flutter_platform_widgets: ^1.9.5
  cupertino_icons: ^1.0.3

  # Fast, Enjoyable & Secure NoSQL Database
  # https://github.com/hivedb/hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  #  This is a simple Service Locator for Dart and Flutter projects
  #  https://pub.dev/packages/get_it
  get_it: ^7.2.0

  # A Flutter plugin project to help with App/Deep Links (Android) and Universal Links and Custom URL schemes (iOS).
  #  https://pub.dev/packages/uni_links
  uni_links: ^0.5.1

  #  A wrapper around InheritedWidget to make them easier to use and more reusable.
  #  https://pub.dev/packages/provider
  provider: ^5.0.0

  #  AutoRoute is a declarative routing solution, where everything needed for navigation is automatically generated for you.
  #  https://pub.dev/packages/auto_route
  auto_route: 2.0.1

  # Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  #  https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.22.0

  #  The google_fonts package for Flutter allows you to easily use any of the 977 fonts
  #  (and their variants) from fonts.google.com in your Flutter app.
  #  https://pub.dev/packages/google_fonts
  google_fonts: ^2.1.0

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.1.0

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: ^2.0.3

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  #  Request Cancellation, File downloading, Timeout etc.
  #  https://pub.dev/packages/dio
  dio: ^4.0.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  # https://pub.dev/packages/intl
  intl: ^0.17.0

  sqflite: ^2.0.0+3

  flutter_map: ^0.13.1
  flutter_map_marker_popup: ^1.0.1
  flutter_map_location: ^0.12.0
  latlong2: ^0.8.0
  location: ^4.3.0
  cached_network_image: ^3.1.0

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

  auto_route_generator: 2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
